<div class="alert alert-block alert-success">
<b>Imported libraries</b>
</div>

In [1]:
import numpy as np
from numpy import random

<div class="alert alert-block alert-info">
<b>Create the matrix</b>
</div>

In [2]:
rl = np.outer(np.ones([5, 1]), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [3]:
im = np.outer(np.linspace(-2, 2, 5), np.ones([5, 1]))
im

array([[-2., -2., -2., -2., -2.],
       [-1., -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [4]:
# Random matrix
n = random.randint(-2, 2, size = (5, 5))
n

array([[ 1, -1,  0,  1, -2],
       [-1, -2,  0,  1,  1],
       [ 0, -2, -1, -2, -1],
       [-2,  1, -1,  0,  0],
       [ 1, -1, -2,  1,  1]])

<div class="alert alert-block alert-info">
<b>Operations</b>
</div>

In [5]:
grid = rl + im
grid

array([[-4., -3., -2., -1.,  0.],
       [-3., -2., -1.,  0.,  1.],
       [-2., -1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [6]:
grid * n

array([[-4.,  3., -0., -1., -0.],
       [ 3.,  4., -0.,  0.,  1.],
       [-0.,  2., -0., -2., -2.],
       [ 2.,  0., -1.,  0.,  0.],
       [ 0., -1., -4.,  3.,  4.]])