***Color manual***

<div class="alert alert-block alert-success">
<b>Green - Libraries</b>
</div>

<div class="alert alert-block alert-info">
<b>Blue - Information</b>
</div>

<div class="alert alert-block alert-danger">
<b>Red - Problems</b>
</div>

***

<div class="alert alert-block alert-success">
<b>Import libraries</b>
</div>

In [11]:
import numpy as np
import sympy as sym

from sympy import * 
from numpy import linalg

<div class="alert alert-block alert-info">
<b>Symbols</b>
</div>

In [3]:
x, y = sym.symbols('x y')

<div class="alert alert-block alert-info">
<b>Random system of equations and solving it (If possible)</b>
</div>

In [4]:
# Input lower and upper limit to the equations variables
min_val = float(input('Choose lower limit: '))
max_val = float(input('Choose upper limit: '))

# Give value to equations
a11 = np.around(np.random.uniform(min_val, max_val), decimals = 2)
a12 = np.around(np.random.uniform(min_val, max_val), decimals = 2)
a13 = np.around(np.random.uniform(min_val, max_val), decimals = 2)

a21 = np.around(np.random.uniform(min_val, max_val), decimals = 2)
a22 = np.around(np.random.uniform(min_val, max_val), decimals = 2)
a23 = np.around(np.random.uniform(min_val, max_val), decimals = 2)

a31 = np.around(np.random.uniform(min_val, max_val), decimals = 2)
a32 = np.around(np.random.uniform(min_val, max_val), decimals = 2)
a33 = np.around(np.random.uniform(min_val, max_val), decimals = 2)

# Create system of equations
eq1 = Eq(a11*x + a12*y, a13)
eq2 = Eq(a21*x + a22*y, a23)
eq3 = Eq(a31*x + a32*y, a33)

print()

# Display system of equations 
print('This is the system of equation:')
display(eq1)
display(eq2)
display(eq3)

# Matrix rows and columns
row1 = [a11, a12, a13]
row2 = [a21, a22, a23]
row3 = [a31, a32, a33]

# Create matrix
matrix = Matrix((row1, row2, row3))

# Display matrix
print('This is the matrix:')
display(matrix)

# Solve the matrix to get the results of the system of equations
print('This is the x and y values to solve the system of equations:')
display(solve_linear_system(matrix, x, y))

Choose lower limit: 1
Choose upper limit: 10

This is the system of equation:


Eq(7.87*x + 9.2*y, 8.19)

Eq(1.59*x + 6.66*y, 1.87)

Eq(2.13*x + 9.49*y, 2.26)

This is the matrix:


Matrix([
[7.87,  9.2, 8.19],
[1.59, 6.66, 1.87],
[2.13, 9.49, 2.26]])

This is the x and y values to solve the system of equations:


None

<div class="alert alert-block alert-info">
<b>System of equations with Sympy</b>
</div>

In [30]:
eq1 = Eq(2*x + 3*y, 5)
eq2 = Eq(4*x + 5*y, 7)
eq3 = Eq(3*x + 5*y, 9)

# System of equations
display(eq1)
display(eq2)
display(eq3)

row1 = [2, 3, 5]
row2 = [4, 5, 7]
row3 = [3, 5, 9]

matrix = Matrix((row1, row2, row3))

# Display the matrix to solve the system
display(matrix)

# Solution for the system
anwser = solve_linear_system(matrix, x, y)
display(anwser)

This is the system of equation:


Eq(2*x + 3*y, 5)

Eq(4*x + 5*y, 7)

Eq(3*x + 5*y, 9)

This is the system of equations matrix:


Matrix([
[2, 3, 5],
[4, 5, 7],
[3, 5, 9]])

This is the x and y values to solve the system of equations:


{y: 3, x: -2}

<div class="alert alert-block alert-info">
<b>System of equations with Numpy</b>
</div>

In [40]:
row1 = [2, -1]
row2 = [3, -1]
cons = [-4, -2]

matrix = np.array([row1, row2])
constants = np.array(cons)

# Display the matrix to solve the system
a = np.matrix([[2, -1, -4], [3, -1, -2]])
print(a)

# Solution for the system
anwser = linalg.solve(matrix, constants)
display(anwser)

[[ 2 -1 -4]
 [ 3 -1 -2]]


array([2., 8.])